server:
  port: 8006

spring:
  application:
    name: cloud-provider-payment
  cloud:
    consul:
      host: 192.168.140.128
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true
        hostname: 192.168.18.3

